import React,{useEffect,useState} from 'react';import {ActivityIndicator,KeyboardAvoidingView,Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';import {StatusBar} from 'expo-status-bar';import {Ionicons} from '@expo/vector-icons';import {api,AppContext,getToken,loadContext,setToken} from './src/api';import {Button,Card} from './src/ui';import {colors} from './src/theme';import {HomeScreen} from './src/screens/HomeScreen';import {UploadScreen} from './src/screens/UploadScreen';import {RecordsScreen} from './src/screens/RecordsScreen';import {VoiceSheet} from './src/screens/VoiceSheet';

type Tab='home'|'upload'|'records';
export default function App(){
  const [token,setAuthToken]=useState<string|null>(null),[ctx,setCtx]=useState<AppContext|null>(null),[loading,setLoading]=useState(true),[tab,setTab]=useState<Tab>('home'),[voice,setVoice]=useState(false);
  async function bootstrap(nextToken?:string){const value=nextToken||await getToken();if(!value){setLoading(false);return}try{setAuthToken(value);setCtx(await loadContext(value))}catch{await setToken(null);setAuthToken(null)}finally{setLoading(false)}}
  useEffect(()=>{bootstrap()},[]);
  async function signedIn(value:string){await setToken(value);setLoading(true);await bootstrap(value)}
  async function logout(){await setToken(null);setAuthToken(null);setCtx(null)}
  if(loading)return <SafeAreaView style={s.center}><ActivityIndicator size="large" color={colors.green}/><Text style={s.muted}>Opening your store…</Text></SafeAreaView>;
  if(!token||!ctx)return <AuthScreen onSignedIn={signedIn}/>;
  return <SafeAreaView style={s.shell}><StatusBar style="dark"/><View style={s.header}><View><Text style={s.brand}>KiranaSaathi</Text><Text style={s.store}>{ctx.business.name}</Text></View><Pressable accessibilityLabel="Sign out" onPress={logout}><Ionicons name="person-circle-outline" size={36} color={colors.green}/></Pressable></View><View style={s.body}>{tab==='home'?<HomeScreen token={token} ctx={ctx} onNavigate={setTab}/>:tab==='upload'?<UploadScreen token={token} ctx={ctx}/>:<RecordsScreen token={token} ctx={ctx}/>}</View><Pressable accessibilityLabel="Talk to KiranaSaathi" onPress={()=>setVoice(true)} style={s.mic}><Ionicons name="mic" size={28} color="#fff"/></Pressable><View style={s.tabs}>{([['home','home','Home'],['upload','camera','Scan'],['records','grid','Business']] as const).map(([key,icon,label])=><Pressable key={key} onPress={()=>setTab(key)} style={s.tab}><Ionicons name={tab===key?icon:`${icon}-outline` as any} size={24} color={tab===key?colors.green:colors.muted}/><Text style={[s.tabText,tab===key&&{color:colors.green}]}>{label}</Text></Pressable>)}</View>{voice&&<VoiceSheet token={token} ctx={ctx} onClose={()=>setVoice(false)} onNavigate={value=>{setVoice(false);setTab(value)}}/>}</SafeAreaView>
}

function AuthScreen({onSignedIn}:{onSignedIn:(token:string)=>Promise<void>}){const [mode,setMode]=useState<'login'|'signup'>('login'),[name,setName]=useState(''),[store,setStore]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(){setBusy(true);setError('');try{const body=mode==='login'?{email,password}:{email,password,name,business_name:store||`${name}'s Store`,city:'Not set',pin_code:'110001',preferred_language:'en'};const result=await api<{access_token:string}>(`/auth/${mode}`,{method:'POST',body:JSON.stringify(body)});await onSignedIn(result.access_token)}catch(e:any){setError(e.message)}finally{setBusy(false)}}return <SafeAreaView style={s.auth}><StatusBar style="dark"/><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={{flex:1}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.authScroll}><View style={s.logo}><Ionicons name="storefront" size={35} color="#fff"/></View><Text style={s.welcome}>{mode==='login'?'Welcome back':'Create your kirana account'}</Text><Text style={s.muted}>Sales, stock, udhaar and insights—now built for your phone.</Text><Card style={{gap:14}}>{mode==='signup'&&<><Field label="Your name" value={name} onChange={setName}/><Field label="Store name" value={store} onChange={setStore}/></>}<Field label="Email" value={email} onChange={setEmail} keyboard="email-address"/><Field label="Password" value={password} onChange={setPassword} secure/>{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}<Button title={mode==='login'?'Log in':'Create account'} onPress={submit} disabled={busy}/><Pressable onPress={()=>{setMode(mode==='login'?'signup':'login');setError('')}}><Text style={s.switch}>{mode==='login'?'New here? Create an account':'Already registered? Log in'}</Text></Pressable></Card></ScrollView></KeyboardAvoidingView></SafeAreaView>}
function Field({label,value,onChange,secure=false,keyboard='default'}:{label:string;value:string;onChange:(x:string)=>void;secure?:boolean;keyboard?:any}){return <View style={{gap:7}}><Text style={s.label}>{label}</Text><TextInput autoCapitalize={keyboard==='email-address'?'none':'words'} keyboardType={keyboard} secureTextEntry={secure} value={value} onChangeText={onChange} style={s.input}/></View>}
const s=StyleSheet.create({shell:{flex:1,backgroundColor:colors.canvas},body:{flex:1},center:{flex:1,alignItems:'center',justifyContent:'center',gap:14,backgroundColor:colors.canvas},header:{height:72,paddingHorizontal:20,backgroundColor:'#fff',borderBottomWidth:1,borderBottomColor:colors.line,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},brand:{fontSize:21,fontWeight:'900',color:colors.greenDark},store:{fontSize:13,color:colors.muted,marginTop:2},tabs:{height:76,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:colors.line,flexDirection:'row',paddingBottom:6},tab:{flex:1,alignItems:'center',justifyContent:'center',gap:3},tabText:{fontSize:12,fontWeight:'700',color:colors.muted},mic:{position:'absolute',bottom:92,right:20,width:62,height:62,borderRadius:31,backgroundColor:colors.green,alignItems:'center',justifyContent:'center',elevation:8},auth:{flex:1,backgroundColor:colors.canvas},authScroll:{flexGrow:1,justifyContent:'center',padding:24,gap:16},logo:{width:66,height:66,borderRadius:20,backgroundColor:colors.green,alignItems:'center',justifyContent:'center'},welcome:{fontSize:32,fontWeight:'900',color:colors.ink,lineHeight:38},muted:{fontSize:15,lineHeight:22,color:colors.muted},label:{fontSize:14,fontWeight:'800',color:colors.ink},input:{minHeight:54,borderRadius:14,borderWidth:1,borderColor:colors.line,backgroundColor:'#FAFCFB',paddingHorizontal:15,fontSize:17,color:colors.ink},error:{color:colors.red,fontWeight:'700'},switch:{textAlign:'center',fontSize:15,fontWeight:'800',color:colors.green}});
